### ISSUE TITLE
credits and main menu text bug

### ISSUE THREAD

**Issue by Bat-Milku** [United-Programming/CursedWoods#8]
steps to recreate: lose the game, game goes back to main menu, then open credits tab
![credits](https://user-images.githubusercontent.com/47035467/186521733-e2393c6f-9f31-424c-92fa-5e131c069f4d.jpg)

**Comment by CPULL** [comment]
Fixed. All previous enemies are now destroyed when moving to the title screen, and the screen itself is bigger and hides tha background.
![image](https://user-images.githubusercontent.com/13871892/186609628-85502f38-d9bb-42c3-9e3b-40d9ea3a6280.png)
